project_name: "theblogs"
languages:
- markdown
- typescript
- yaml
ignore_all_files_in_gitignore: true
ignored_paths:
- node_modules
- public
- .deploy_git
- _logs
- _archive
- .obsidian
- .trash
read_only: false
excluded_tools: []
included_optional_tools: []
initial_prompt: ""
encoding: utf-8

